##############
# Yaml Anchors
##############
# Install Kurtosis CLI
install_and_start_kurtosis: &install_and_start_kurtosis
  run: |
    echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
    sudo apt update
    sudo apt install kurtosis-cli
    kurtosis config init dont-send-metrics
    kurtosis cluster set docker
    kurtosis engine start

##############
# CircleCI
##############
version: 2.1

orbs:
  slack: circleci/slack@4.10.1

executors:
  ubuntu_vm:
    machine:
      image: ubuntu-2004:2023.04.2

jobs:
  run_test:
    # strictly speaking we don't "need" this(large) but we are continuously adding new examples
    resource_class: large
    executor: ubuntu_vm
    steps:
      - checkout
      - <<: *install_and_start_kurtosis

      - run:
          name: Run the ./scripts/run.sh in each subdirectory
          no_output_timeout: 30m
          command: |
            set -euo pipefail
            skip_dirs=(".circleci/ .github/ data-package/")
            for directory in */ ; do
              if git --no-pager diff --exit-code origin/main...HEAD -- ':.circleci' ":${directory%/}"; then
                continue
              fi            
              if ! echo "$skip_dirs" | grep -q "$directory"; then
                "./${directory}scripts/run.sh"
                kurtosis clean -a
              fi
            done


workflows:
  run_test:
    jobs:
      - run_test:
